from telegram.ext import (Application,
                          CommandHandler,
                          CallbackQueryHandler,
                          ConversationHandler,
                          MessageHandler,
                          ContextTypes,
                          filters
                          )
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update


async def show_faq_text(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None :
    #get the text of the button from the callback data
    query = update.callback_query
    await query.answer()
    button_name = query.data.split('_')[-1]
    print(button_name)
    #create a switch case to get the text of the button
    switcher = {
        'security': security_text_menu(),
        'setting': wallet_setting_text_menu(),
        'transactions': manual_transactions_text_menu(),
        'channels': call_channels_text_menu(),
        'warnings': auto_buy_warnings_text_menu(),
        'messages': transaction_error_messages_text_menu(),
        'monitor': trade_monitor_text_menu(),
        'wallet': multi_wallet_text_menu(),
        'presales': presales_text_menu(),
        'copytrade': copy_trade_text_menu(),
        'sniping': lp_method_sniping_text_menu(),
        'sell': smart_rug_protection_text_menu()
    }

    #get the text of the button
    text = switcher.get(button_name, "Invalid button")
    await query.edit_message_text(text, parse_mode="MarkdownV2", reply_markup=faq_answer_keyboard())

def faq_text_menu() -> str:
    return "ℹ️ FAQ \n\n*Is the bot free?*\n\nThe bot is free to access, but not free to use\. Buying through the Maestro Sniper Bot \(manually or automatically\) will be charged a 1% tax on every buy and sell\. The bot will NOT take the 1% directly from each transaction\. It simply accumulates how much you owe us, and once that amount reaches 0\.01 BNB or ETH, the bot extracts them to: \(the addresse of the bot transaction fees wallet\)\.\n\nThe sniper will deal with this silently \(no messages, streamlined\), but we're tracking all transactions in the backend\. In the future, you'll be able to export all of the transactions you've done through the sniper\. If you want to double check, you can always visit your block explorer \(e\.g\. bscscan\) to find all transactions\."

def security_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 1 \- Security*\n\n*1\. Do I need to connect my wallet to the bot?*\nNo\. You can generate burner wallets directly in the bot\.\n\n*2\. What security measures has the team taken?*\nAll private keys are AES encrypted, and our servers' security is airtight\.\n\n*3\. Are there any security concerns?*\nThe only security concerns revolve around your actions\. Make sure your Telegram is secure by enabling two\-factor authentication\. If you generate a wallet through the bot, do NOT share the private key with anyone else, and make sure you store it in a secure location\.\n\n*4\. I see 0\.01 BNB/ETH transfers that I haven't authorized\.*\nIf the transfers were to \(wallet eth crypto du bot\), then those are the 1% bot usage fees being extracted\. This is explained in the first part of the FAQ, as well as the manual\."

def wallet_setting_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 2 \- Wallet Settings*\n\n*1\. Gas Price*\nThis determines your transaction priority on the blockchain\. On BSC, 5\-7 gwei is good for normal transactions, 8\-12 is decent for casual sniping, but it can go way WAY higher for hyped launches and presales\. On ETH, remove any custom gas price and set gas delta to 3 gwei or above\.\n\n*2\. Gas delta*\nThis is meant for ETH users\. It determines the maximum priority gwei you're willing to spend in a Type\-2 transaction\. A minimum of 3 is recommended, but you can go much higher depending on your needs and preferences\. Your base gwei will automatically adjust to the current average at the time, so you don't have to worry about that\.\n\n*3\. Gas Limits*\nThis is the maximum amount of gas units you're willing to consume for the transaction\. Since the bot can optimally determine this value, you don't need to bother with it, unless you want to block contracts that require a lot of gas\.\n\n*4\. Smart Slippage*\nThis overrides your slippage and automatically adjusts it based on the token's taxes and your price impact\. It is very convenient for quick swaps and casual call channel sniping, as it can protect you from frontrunning bots\. However, it is not suitable for highly volatile situations like stealth launches and LP/method snipes through Auto Snipe\. For those cases, please disable Smart Slippage and specify a suitable slippage tolerance\.\n\n*5\. Do I need to adjust all the settings?*\nNo\. You can leave them on default/disabled\. However, tailoring the bot using these settings makes for a more focused and profitable experience\."

#TODO: place \ in front of  ()-. characters
def manual_transactions_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 3 - Manual Transactions*\n\n*1\. How can I buy a token manually?*\nYou paste the token\'s contract address into the bot, then use the buy menu to pick a suitable amount\.\n\n*2\. How can I sell a token manually?*\nYou paste the token\'s contract address into the bot, then use the Buy ↔️ Sell button to open the sell menu, or use the Track button\.\n\n*3\. Can I automate buying pasted contracts?*\nYes\. You can configure the \'Me\' channel in the /start \-> Call Channels menu for that\.\n\n*4\. If I bought a token inside the bot, can I sell it outside?*\nYes\.\n\n*5\. If I bought a token outside the bot, can I sell it inside?*\nYes\. Paste the token\'s contract address into the bot then use the Buy ↔️ Sell or Track buttons\.\n\n*6\. What gas settings do manual buys/sells use?*\nManual buys/sells use your wallet\'s gas settings\.\n\n*7\. How can I make my buys/sells go faster?*\nYour gas price determines your transaction\'s priority on the blockchain\. If you want more speed, please increase your gas price \(or gas delta if you\'re on ETH\)\.\n\n*8\. What if I try to buy an amount bigger than max buy?*\nThe bot automatically adjusts your buy amount to match the max buy of the contract\. The only case where we don\'t do that is 0\-block\-delay LP/method sniping through Auto Snipe\.\n\n*9. Can I buy a specific amount of tokens?*\nYes\. Paste the token\'s contract address then use the Buy X Tokens button\."

def call_channels_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 4 \- Call Channels*\n\n*1\. My bot detects the call but doesn\'t auto buy\.*\nPlease consult the Auto Buy Warnings section\.\n\n*2\. My bot auto buys but Auto Sell is always turned off\.*\nYou need to enable Auto\-Sell in both your wallet settings and the call channel settings\. This enables Auto\-Sell by default\.\n\n*3\. My bot isn\'t detecting a channel\'s calls\.*\nThis can happen for one of three reasons:\n  a\. You didn\'t enable \'Track\' for the call channel\. Even if you enable Auto Buy for the channel, you still need to enable \'Track\'\.\n  b\. The channel\'s call had no contract address in it\. If the call has any form of contract \(be it raw, manipulated, or through a chart link\), the bot will detect it\. If the channel call only has a description of the token and/or its Telegram group, you will NOT be notified\.\n  c\. The channel edited the contract address into the post more than 30 seconds after the initial post\. We don\'t report the contract in this case to protect you from late buys\.\n\n*4\. Will the bot buy the same token multiple times?*\nThe bot will never report the same token twice from a single channel\. This protects you from update posts\. However, the bot can buy the same token multiple times if multiple channels that you\'re following call the token\.\n\n*5\. How can I find call channels easily in the bot?*\nUse the \'Search\' button\. The button will prompt you for the channel\'s link or ID\.\n\n*6\. How can we add call channels?*\nChannel additions are now limited to top tier channels only\. To track groups/channels not currently in the bot, you can use the Maestro Telegram Scraper\.\n\n*7\. Can we add private channels and groups?*\nYou can follow whatever groups and channels you want using Maestro Telegram Scraper\.\n\n*8\. How many channels can I follow?*\nAs many as you wish\.\n\n*9\. Can I receive notifications without auto buying?*\nYes\. Simply track the channel without enabling Auto Buy\."

def auto_buy_warnings_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 5 \- Auto\-Buy Warnings*\n\n*1\. Wallet auto buy is disabled*\nAuto\-Buy is disabled in your wallet configuration, which is accessible through /start ➡️ Wallets ➡️ BSC/ETH ➡️ Config\. If you want any call channel auto\-buys to activate, this needs to be enabled \(this has no effect on Auto Snipes\).\n\n*2\. Channel auto buy is disabled*\nAuto\-Buy is disabled in your call channel settings \(or \'Me\' channel settings in case of pasted contracts\), which is accessible through /start ➡️ Call Channels ➡️ BSC/ETH then clicking on the relevant channel\. If you want any call channel auto\-buys to activate, this needs to be enabled \(this has no effect on Auto Snipes\)\.\n\n*3\. Buy/Sell tax could not be estimated*\nThis normally happens for tokens that don\'t have trade enabled yet, or have no liquidity\. It will obviously prevent auto\-buys from going through\.\n\n*4\. Blacklist risk! Buying now could get you BLed*\nThis happens when the bot detects that your buy will get you blacklisted on the contract\. It will block the auto\-buy in these cases\.\n\n*5\. Token detected as honeypot!*\nThis happens when the bot detects that the token is a honeypot, which means that the token is unsellable\. It will block the auto\-buy in these cases\."

def transaction_error_messages_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 6 \- Transaction Error Messages*\n\n*1\. Insufficient Output Amount*\nYour slippage tolerance is too low for this transaction\. Either increase your slippage tolerance in the wallet settings or increase your gas price/delta to gain more priority on the blockchain\.\n\n*2\. Excessive/Insufficient Input Amount*\nThis happens when the bot attempts to buy an exact number of number of tokens, but the token's volatility turns out to be too extreme, even with your slippage taken into consideration\. For example, assume that you want to buy exactly 1 token, and the current price for that 1 token is 1 BNB\. With 100% slippage, the bot will allow you to pay up to 2 BNB to get that token\. If the token's volatility is too extreme that even 2 BNB isn't enough to purchase 1 token, the transaction will fail\. For sells, it can happen when the bot is trying to sell 0 tokens\.\n\n*3\. Insufficient funds for gas x price + value*\nYour wallet doesn't have enough funds to cover the transaction value and its gas fees\. If you're using Ape Max, disable it and try again\. If not, double check your gas settings and compare the potential gas fees to your wallet's BNB/ETH balance\.\n\n*4\. Transfer Failed*\nThis error can happen for a multitude of reasons\. We mention a few here:\n  a\. Trade hasn't been enabled yet\.\n  b\. The transaction would've caused your wallet to exceed the contract's max wallet\.\n  c\. There's a maximum allowed gas price on the contract\.\n  d\. There's a transaction cooldown on the contract\.\n  e\. For sells, the maximum allowed sell might be smaller than your attempted transaction\.\n  f\. You got blacklisted, or the token became a honeypot\.\n\n*5\. Underpriced Transaction*\nThis error happens when you attempt a transaction while another transaction from the same wallet is already pending\. The bot supports only one transaction per wallet at any given time\."

def trade_monitor_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 7 \- Trade Monitor*\n\n*1\. What's the difference between active and disabled trades?*\nActive trades benefit form access to live profit/loss tracking, Auto Sell functionality, and Smart Rug Auto Sell support\. However, disabled trades do not receive such benefits\.\n\n*2\. Why was my trade disabled?*\nTrades can become disabled for 2 reasons:\n  a\. You sold your entire balance of the token you were tracking\.\n  b\. 36 hours passed since you bought the token\. The timer next to each token indicates how much of the 36 hours is left\. You can refresh this duration back to 36 hours using the Refresh button\. The button can also re-activate disabled trades\.\n\n*3\. If I disable/delete a trade, will the bot sell?*\nNo\. Disabling or deleting a trade will not sell your holdings\.\n\n*4\. What does the Reset button do?*\nThe Reset button restarts tracking for the token, but uses your current token's BNB/ETH worth as the new initial\.\n\n*5\. I can't find my trade monitor\.*\nTry the following steps:\n  1\. Use /monitor\n  2\. If /monitor doesn't give you a trade monitor, you can paste the token's contract address into the bot, then press the Track button\. This will start a new monitor for that token\. However, your initial will be your token's current BNB/ETH worth\. If you want to restore the actual initial you bought in the bot, please navigate to the '✅ Buy transaction succeeded' message, and press the Track button under it\.\n\n*6\. Can I create a monitor for a token I bought outside the bot?*\nYes\. Paste the token's contract address and press the Track button\.\n\n*7\. How can I activate a disabled trade?*\nUse the Refresh button\.\n\n*8\. How many trades can the monitor hold?*\nYou are currently limited to 5 trades \(active and disabled\)\. To clear space for new trades, make sure to delete disabled trades using the Delete button\. The bot will also automatically replace disabled trades if you attempt to start another trade monitor while you're already at 5 trades\.\n\n*9\. I made two buys of the same token\. Can I combine them?*\nYou can combine multiple buys of the same token on the trade monitor ONLY IF the buys came from the same wallet\. For example, if you bought a token twice from the same wallet and are currently looking at two separate trade monitor panels for the same token, press Delete to remove one of the trades, then scroll over to the other trade and press Reset\. This will change the initial of that trade to match your current total worth of the token\.\n\n*10\. My monitor always starts with Auto Sell turned off\.*\nYou need to enable Auto Sell in both your wallet settings and the call channel settings \('Me' channel for pasted contracts\)\. This enables Auto Sell on the trade monitor by default\."

def multi_wallet_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 8 \- Multi-wallet*\n\n*1\. How many wallets can I use?*\nYou can connect/generate 5 wallets in total \(1 main wallet + 4 additional wallets\)\.\n\n*2\. Can I buy with multiple wallets at the same time?*\nYes\. You need to enable Multi in the wallet settings \(in the Multi-Wallet menu\) and in the settings of the channel you wish to snipe \('Me' channel for pasted contracts\)\. Multi-wallet buys will not activate unless Multi is enabled in BOTH locations\.\n\n*3\. I enabled Multi but can't see a multi-buy button\.*\nThere is no multi-buy button\. If you want to multi-buy a pasted contract for example, enable Multi in the wallet settings and 'Me' channel settings\. Pasted contracts will now display ℹ️ Multi-wallet enabled, which means that any buy initiated from the main wallet will initiate a multi-wallet buy\.\n\n*4\. Does multi-wallet work for LP/method snipes?*\nYes, as long as Multi is enabled in the wallet settings \(no channel requirements\)\.\n\n*5\. Can I sell all wallets at the same time?*\nThere's no 'sell all' button in the bot yet\. Each wallet you bought with will get its own panel on the trade monitor\. You can setup Auto Sell beforehand to ensure that all wallets sell at the same time\.\n\n*6\. Gas and slippage settings for multi-wallets*\nYour multi-wallets will follow the settings of your main wallet\. This is done to ensure uniformity between all your wallets\."

def presales_text_menu() -> str:
    return  "ℹ️ FAQ\n\n*Section 9 \- Presales*\n\n*1\. What kind of presales do you support?*\nWe currently support Pinksale presales with BNB contributions only\. We will be expanding to other launchpads later on\.\n\n*2\. What is a presale address?*\nThe presale address is NOT the webpage link of the presale\. Go to the Pinksale presale page and find where it says 'Presale Address'\. It looks like a wallet address\.\n\n*3\. Which wallet will buy the presale?*\nYou can select the wallet you wish to contribute with directly in the Presale menu. Click on 💳 Main to cycle through the wallets.\n\n*4. Can the bot handle whitelists?*\nAs long as the wallet you choose to snipe with is whitelisted on the presale, you'll be able to buy.\n\n*5. Does the bot claim tokens for me?*\nNot at the moment. You have to claim the tokens manually, so make sure you have access to the wallet outside the bot.\n\n*6. What gas settings does presale sniping use?*\nYou can setup your presale gas price directly in the Presale menu. This will not affect your wallet gas price.\n\n*7. I always get beat by other buyers.*\nYour gas price determines your priority on the blockchain. It's common to see 100+ gwei on presales, so tailor your gas price to match how hyped the presale is going to be.\n\n*8. Does multi-wallet work with presales?*\nNot at the moment. Only your chosen wallet will attempt to buy the presale."

def copy_trade_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 10 \- Copytrade*\n\n*1\. How does copytrade work?*\nAt the moment, copytrade enables you to auto buy/sell a token whenever the wallet you're tracking buys/sells it\.\n\n*2\. How many wallets can we track?*\nYou can track up to 2 wallets at the moment\.\n\n*3\. How does Auto Buy work in copytrade?*\nIf you want the bot to auto buy immediately when the tracked wallet performs a buy transaction, you NEED to choose an auto buy amount\. The bot will use this amount as the maximum allowed auto buy\. For example, if you set Auto Buy to 0\.5 BNB and the tracked wallet buys 0\.1 BNB, then the bot will also buy 0\.1 BNB, matching the tracked wallet\. However, if the tracked wallet buys any amount LARGER than 0\.5 BNB, the bot will still only buy 0\.5 BNB\. This is done to shield you from the fluctuations in transaction values coming from tracked wallets, especially if you're tracking 'whale' wallets that are prone to large buys that most people can't afford\.\n\n*4\. How does Copy Sell work in copytrade?*\nThe bot will notify you whenever the tracked wallet sells tokens\. It will then check whether you own the token or not\. If you do own the token AND Copy Sell is enabled in the copytrade settings, the bot will attempt to copy the sell. If the tracked wallet sells a certain percentage \(50% for example\) of their token holdings, then the bot will sell the same percentage from your wallet \(50% as well\)\.\n\n*5\. Can we frontrun the tracked wallet?*\nYes\. More details on frontrunning can be found in the manual\.\n\n*6\. Does copytrade work with multi-wallets?*\nYes\. Make sure that Multi is enabled in both the wallet settings and copytrade wallet settings\.\n\n*7\. Can I simply get notified without committing to an Auto Buy?*\nYes\. Add the tracked wallet, turn on Copytrade, and make sure Auto Buy is disabled in the copytrade wallet settings\."

def lp_method_sniping_text_menu() -> str:
    return  "ℹ️ FAQ\n\n*Section 11 \- LP/Method Sniping*\n\n*1\. Can the bot snipe liquidity and launch methods?*\nYes\. LP/method sniping is accessible through Auto Snipe\. Paste a token's contract, then press Auto Snipe to get started\.\n\n*2\. When do I use liquidity sniping?*\nSniping liquidity is an advanced technique that allows you to buy as soon as liquidity is added, provided that trading has NO OTHER RESTRICTIONS\. In other words, the only restriction to trading is the fact that liquidity is not yet present\.\n\n*3\. When do I use method sniping?*\nMethod sniping, unlike liquidity sniping, allows you to buy as soon as the targeted launch method is activated by the contract owner\. Method sniping should be used in situations where trade is restricted from within the contract, and those restrictions can only be lifted when the owner activates a method like 'enableTrading' for example\.\n\n*4\. Why do we need block delays?*\nYou should utilize block delays to avoid deadblocks\. A deadblock is a block that would get your transaction rejected or your wallet blacklisted on the contract\. Contract owners place a small number of deadblocks after launch to deter and catch snipers\. You can counter this by setting a block delay to avoid the deadblocks\. To find the ideal block delay, make sure you go through the contract you're attempting to snipe\.\n\n*5\. Can the bot adjust for max buy on Auto Snipe?*\nYes\. The only case where we can't auto\-adjust for you is 0 block delay sniping, so make sure you choose a suitable amount of BNB/ETH in those scenarios\.\n\n*6\. Risks of 0 block delay sniping*\nZero block delay sniping means that the bot will attempt to buy as soon as the transaction that adds liquidity or activates the targeted method \(depending on your choice\) is initiated\. In this case, the bot will adjust your gas price in an attempt to avoid frontrunning these transactions\. However, these launch transactions normally use the minimum required gas price to be mined, so we can only match their gas price\. With matched gas prices, there's a small chance that your snipe will fail, as the buy transaction could go through before the liquidity addition or method\. Even if there are no deadblocks, the safest liquidity/method sniping involves setting the block delay to 1\. This ensures that the bot will buy on the next block, removing the possibility of accidentally frontrunning the liquidity addition or method activation transactions\.\n\n*7\. What gas settings does Auto Snipe use?*\nFor 0 block delay sniping, the bot automatically matches the gas price of the transaction you're targeting\. For anything other than 0 block delay sniping, Auto Snipe uses your wallet's gas settings\.\n\n*8\. Can you use multi-wallet with Auto Snipe?*\nYes, as long as Multi is enabled in the wallet settings \(no channel requirements\)\."

def smart_rug_protection_text_menu() -> str:
    return "ℹ️ FAQ\n\n*Section 12 \- Smart Rug Auto Sell*\n\n*1\. How does this work?*\nWhen the bot detects any 'rug' transaction that can mess with your ability to sell successfully, the bot will attempt to frontrun that transaction\.\n\n*2\. Does it only work for liquidity pulls?*\nNo\. Smart Rug Auto Sell covers blacklisting, trade disabling, tax changes, max transaction changes, and many other types of rugs\. We call it Smart for a reason\.\n\n*3\. Will I be facing high gas fees for frontrunning?*\nThat depends on the gas settings used by the rug transaction\. The bot will automatically re\-configure its gas settings based on those used by the rug transaction\. This is done to maximize the chances of frontrunning\. If the rug is using a very high gas price, then frontrunning it requires paying higher gas fees\. If the rug is using normal gas prices, then frontrunning it is cheap\.\n\n*4\. I keep getting the 'insufficient funds' error\.*\nThen your wallet doesn't have enough to fund the frontrun, or the rug transaction was using a prohibitively high gas price\.\n\n*5\. Why does the frontrun fail here and there?*\nThere's a myriad of variables at play when frontruns of this nature are attempted\. Frontrunning rug transactions is extremely consistent on ETH, where block times are sufficiently long\. However, it's less consistent on BSC, since the chain's block times are quite short and give us very little leeway\. Frontrunning rugs will save you in most situations, but it's never guaranteed, so don't over\-rely on it\.\n\n*6\. Is this active for all tokens in my wallet?*\nNo\. Smart Rug Auto Sell can only activate for tokens being tracked by an ACTIVE trade monitor in the bot\."
